name: filmoteca
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  youtube_player_iframe: ^4.0.4

  cupertino_icons: ^1.0.8

  # Dependencies untuk Filmoteca
  http: ^1.2.2
  shared_preferences: ^2.3.2
  cached_network_image: ^3.3.1
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.11.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png

# Configuration for flutter_launcher_icons. After adding your icon image
# at `assets/icon.png`, run:
#   flutter pub get
#   flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
